{
  "contract": "send_loop",
  "tool": "mythril",
  "start": 1563372332.7126787,
  "end": 1563372343.8619277,
  "duration": 11.149249076843262,
  "analysis": {
    "error": null,
    "issues": [
      {
        "address": 431,
        "code": "refundAddresses[x].send(refunds[refundAddresses[x]])",
        "debug": "",
        "description": "Multiple sends exist in one transaction, try to isolate each external call into its own transaction. As external calls can fail accidentally or deliberately.\nConsecutive calls: \nCall at address: 431\nCall at address: 431\nCall at address: 431\n",
        "filename": "/dataset/unchecked_low_level_calls/send_loop.sol",
        "function": "refundAll()",
        "lineno": 22,
        "title": "Multiple Calls",
        "type": "Information"
      }
    ],
    "success": true
  }
}